// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SiteImage {
  image_id: string;
  uploaded: boolean;
  original_file_name: string;
  source_url: string;
  image_type: string;
  collection_id: string;
}
