// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collection } from "./Collection";

export interface Site { name: string, id: string, collections: Array<Collection>, }