// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteImage } from "./SiteImage";

export interface Collection { collection_id: string, name: string, images: Array<SiteImage>, }