// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Collection { collection_id: string, collection_name: string, collection_key: string, site_id: string, }